### ISSUE TITLE
Complete Parameter List edit on github link broken 

### ISSUE THREAD

**Issue by ctech4285** [ArduPilot/ardupilot_wiki#500] opened 2016-07-27 20:08 UTC
[Complete Parameter List](http://ardupilot.org/copter/docs/parameters.html) 

The edit on github link on this page resolves to 404 error  https://github.com/ArduPilot/ardupilot_wiki/blob/master/copter/source/docs/parameters.rst

**Comment by hamishwillee** [comment] 2016-07-27 23:15
Thanks @ctech4285,

Arggg - I thought I'd killed that link in the theme :-(. It shouldn't appear at all because this page is generated from the ardupilot source code. 

Assigned to me. I'll look at some point soon hopefully.

**Comment by gmorph** [comment] 2016-11-15 22:57
I've confirmed this is still an issue.

**Comment by auturgy** [comment] 2017-10-15 01:35
@OlivierJB @hamishwillee can this be fixed?  Should be simple for someone with access to and familiarity with the theme.

**Comment by hamishwillee** [comment] 2017-10-15 11:07
Yes, but requires a little research (which I do not have time for right now).

The edit link is dynamically created based on page name/url to point to the right place in github. The reason it fails is that the source for this page *is not in github* - the page is dynamically generated by a script at build time from source.

The solution is to hide the edit link on the page altogether. I'm no longer sure how to do that. BUT I did kill the edit link on the home page, so there must be some theme code to make this happen already. Probably just needs to also include the parameters page.

**Comment by Hwurzburg** [comment] 2019-11-02 20:01
@hamishwillee any progress on this??

**Comment by hamishwillee** [comment] 2019-11-03 05:05
See link above. I hope you can test it for me?

**Closed** 2019-11-03 22:28 UTC
Labels: common-wiki, infrastructure
