### ISSUE TITLE
DEV: Create install from Windows 11 with WSLg - this is graphics engine for Linux  

### ISSUE THREAD

**Issue by K2AAE** [ArduPilot/ardupilot_wiki#4043] opened 2022-01-14 01:23 UTC
I just finished installing on Windows 11 with WSLg and Ubuntu 20.04, this could be added to the Wiki

**Comment by hendjoshsr71** [comment] 2022-01-14 01:27
Closing this as it is a duplicate of this issue. https://github.com/ArduPilot/ardupilot_wiki/issues/3911

If you have any hints or items you think should be on the page please add it to the other issue! Or even better a PR! :)

**Closed by hendjoshsr71** 2022-01-14 01:27 UTC
