### ISSUE TITLE
Indoor test Hex HereFlow Optical Flow Sensor cannot be armed in Loiter mode

### ISSUE THREAD

**Issue by LiaoYiDe** [ArduPilot/ardupilot_wiki#5095] opened 2023-04-29 02:03 UTC
Here flow settings refer to the following URL: https://ardupilot.org/copter/docs/common-optical-flow-sensor-setup.html#common-optical-flow-sensor-setup

- The result of Calibrating the sensor is shown in the figure below

![hereflow_cal_OFflowYOFbodyYIMUGyrY](https://user-images.githubusercontent.com/47845460/235278388-ca2ad6af-ddcc-4bd6-b54f-ddb26543fcee.png)
![hereflow_cal_OFflowXOFbodyXIMUGyrX](https://user-images.githubusercontent.com/47845460/235278389-82f78fa3-b72a-44b3-aee4-2ef4bd55ba86.png)

- The result of First Flight (stablize flight mode) is shown in the figure below

![hereflow_stablize_OFbodyxIMUGyrX](https://user-images.githubusercontent.com/47845460/235278409-fc39bedd-d6ab-4fc5-b23f-de481ee3481c.png)
![hereflow_stablize_OFbodyYIMUGyrY](https://user-images.githubusercontent.com/47845460/235278414-b978f6b7-deee-4a3a-8444-215e969951e2.png)

I think both Calibrating the sensor and First Flight are consistent with URL teaching,
But when Second Flight is going to take off in loiter mode, the mission planner will display a "need position estimates" warning message and cannot be ARMED.
I tried to adjust the rngfnd1_min value of the here flow based on the information I found, and I tried to change it to a value of -150~20, but it didn't work.
If anyone knows the problem, please give me some advice, thank you!!

**Comment by rmackay9** [comment] 2023-04-30 23:00
Hi @LiaoYiDe,

I suspect the issue is that the vehicle doesn't have a working rangefinder.  The other possibility is that the EKF origin hasn't been set which can be done by right-mouse-button clicking on the MP map and selecting, Set Home Here >> Set EKF Origin.

This is a flight code support issue so it really should go into [the forums](https://discuss.ardupilot.org/c/arducopter/copter43/167) so I will close this issue.  sorry to be strict but if we're not then our wiki and flight code to-do list (which is what these issues lists are for) turn into another support forum.

**Closed by rmackay9** 2023-04-30 23:00 UTC
