### ISSUE TITLE
throttle below failsafe

### ISSUE THREAD

**Issue by Merik311** [ArduPilot/ardupilot_wiki#1117] opened 2018-03-08 20:04 UTC
[Simple GeoFence](http://ardupilot.org/copter/docs/ac2_simple_geofence.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by auturgy** [comment] 2018-03-13 06:50
It isn't clear what the issue is.  Please provide details, so we can better understand the problem.
What would be awesome is if you could click the "edit in github" button at the top right of the wiki page and have a go at making a fix!

**Comment by Hwurzburg** [comment] 2019-11-10 20:56
no input....closing

**Closed by Hwurzburg** 2019-11-10 20:56 UTC
