### ISSUE TITLE
add "Trusted, Versatile, Open" to logos on wiki

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#2285] opened 2019-12-01 03:54 UTC
We should have "Trusted, Versatile, Open" in several places in our wiki. Key places are:

 - under the 'ArduPilot' logo on ardupilot.org
 - under the ArduPilot logo in left bar on http://ardupilot.org/ardupilot/
 - under ArduPilot logo on each vehicle page

It has been our motto for a long time, but we've never pushed it out so is not widely known

**Comment by Hwurzburg** [comment] 2019-12-01 13:47
cant seem to find an ArduPilot logo on a vehicle page, index nor intro..can you point it out?
we should assign this to whomever can edit the concrete

**Comment by tridge** [comment] 2019-12-02 00:50
I think we should have "ArduPilot" with "trusted, versatile, open" at least on front page of every vehicle wiki, at top of left hand menu. Perhaps on every page that displays that left colum menu?

**Comment by tridge** [comment] 2019-12-02 00:51
we should also start the process of removing the big "ArduPlane" and similar images, and use ArduPilot consistently

**Comment by auturgy** [comment] 2019-12-07 01:17
Duplicate of https://github.com/ArduPilot/ardupilot_wiki/issues/1091
They can probably both be closed: thanks @Hwurzburg

**Closed** 2019-12-07 04:13 UTC
